component_dict:
  Resistor:
    module_path: entrenador_electronico.source.components.ResistorComponent
    class_name: ResistorComponent
  Light:
    module_path: entrenador_electronico.source.components.LightComponent
    class_name: LightComponent