general:
  width: 800
  height: 500

component_dict:
  resistor:
    module_path: entrenador_electronico.source.components.ResistorComponent
    class_name: ResistorComponent
    default_name: Resistor
    default_shortname: R
    default_value: 150
    default_unit: ohm
  light:
    module_path: entrenador_electronico.source.components.LightComponent
    class_name: LightComponent
    default_name: Light
    default_shortname: L
    default_value:
    default_unit: